export { StatCard } from './stat-card'
export { StageBadge } from './stage-badge'
export { TemperatureBadge } from './temperature-badge'
export { CognitiveGauge } from './cognitive-gauge'
export { ChannelIcon, ChannelLabel } from './channel-icon'
export { CarnalIcon, getCarnalConfig, CARNALES } from './carnal-icon'
export type { CarnalConfig } from './carnal-icon'
